### ISSUE TITLE
Test broken, maven still "success"

### ISSUE THREAD

**Issue by joshiste** [chkal/frontend-boilerplate#1]
When in clone your repo and do a `mvn install` right away I see some errors from transpiling the tests but the build doesn't fail.
[log.txt](https://github.com/chkal/frontend-boilerplate/files/164589/log.txt)

**Comment by chkal** [comment]
Yeah, I see. There are errors reported by the TypeScript compile because it doesn't know about the Jasmine testing library. But actually the code works fine. That's some weird thing about TypeScript. Even if TypeScript doesn't know about specific types it nevertheless compiles and creates working code. Actually I'm not sure why TypeScript doesn't report this as a warning. But this can be fixed by telling TypeScript about the types. I'll address this as soon as I find some time. Thanks for reporting.

**Comment by chkal** [comment]
BTW: I'll be at the Early Adopter Area today. So I could show some stuff on my laptop.

**Comment by chkal** [comment]
I've converted the test from a TypeScript to a standard ES6 file. Actually I often use non-TypeScript files for tests and TypeScript for the actual code...
